import numpy as np

from framework_core import ContinuumSimulation
from module_wave_genetics.wave_genetics_dna_oscillator import (
    WaveGeneticsDNAOscillator,
)


class MolecularPhaseChemistry:
    """
    Conceptual module for molecular phase chemistry.

    The module represents molecular bonding not as a purely mechanical
    interaction between static particles, but as topological phase-locking
    of nonlinear oscillator groups inside a liquid medium.

    Within the open nonlinear dissipative dynamic Continuum, chemical bonds
    are modeled as stable phase relations between atomic or molecular
    resonators. The liquid medium is represented as a memory-bearing coupling
    substrate that can be modulated by biophoton forcing and residual
    phantom-field coherence.

    The module also includes a chemical appearance layer:
    a numerical indicator of how strongly molecular bonding is manifested
    as a retained phase-chemical structure.
    """

    def __init__(
        self,
        num_resonators: int = 32,
        medium_viscosity: float = 0.1,
        seed: int | None = None,
    ):
        """
        Initialize the molecular phase-chemistry cluster.

        Parameters
        ----------
        num_resonators:
            Number of atomic or molecular oscillators in the cluster.
        medium_viscosity:
            Viscosity of the liquid medium.
            It acts as a damping factor for phase coupling.
        seed:
            Optional random seed for reproducible experiments.
        """
        if num_resonators <= 0:
            raise ValueError("num_resonators must be positive.")
        if medium_viscosity < 0:
            raise ValueError("medium_viscosity must be non-negative.")

        self.num_resonators = num_resonators
        self.eta = medium_viscosity
        self.rng = np.random.default_rng(seed)

        # Intrinsic frequencies of atomic or molecular resonators.
        self.atomic_frequencies = self.rng.uniform(
            20.0,
            50.0,
            num_resonators,
        )

        # Current phase state of molecular oscillators.
        self.molecular_phases = self.rng.uniform(
            0.0,
            2.0 * np.pi,
            num_resonators,
        )

        # Topological phase-bonding matrix.
        self.binding_matrix = np.zeros(
            (num_resonators, num_resonators),
            dtype=np.float64,
        )

        # Structural memory tensor of the liquid medium.
        self.medium_memory_tensor = np.zeros(
            (num_resonators, num_resonators),
            dtype=np.float64,
        )

        # Chemical appearance layer:
        # numerical indicator of retained molecular manifestation.
        self.chemical_appearance_index = 0.0

    def apply_biophoton_forcing(
        self,
        biophoton_signal: np.ndarray,
        phantom_coherence: float,
    ) -> None:
        """
        Apply biophoton or phantom-field forcing to the liquid medium.

        Parameters
        ----------
        biophoton_signal:
            Input biophoton signal generated by the DNA oscillator.
        phantom_coherence:
            Residual coherence of the phantom field.
        """
        if phantom_coherence < 0:
            raise ValueError("phantom_coherence must be non-negative.")

        if biophoton_signal.size == 0:
            return

        # Interpolate the biological signal onto the molecular resonator basis.
        forcing_pattern = np.interp(
            np.linspace(0.0, 1.0, self.num_resonators),
            np.linspace(0.0, 1.0, biophoton_signal.size),
            biophoton_signal,
        )

        # Phantom coherence scales the effective forcing amplitude.
        forcing_amplitude = forcing_pattern * phantom_coherence

        # Nonlinear imprinting of the forcing pattern into the medium memory.
        self.medium_memory_tensor += (
            np.outer(forcing_amplitude, forcing_amplitude) * 0.1
        )

        # Saturation limit of the medium memory.
        self.medium_memory_tensor = np.clip(
            self.medium_memory_tensor,
            -2.0,
            2.0,
        )

    def synchronize_molecular_bonds(self, dt: float = 0.01) -> float:
        """
        Execute one step of molecular phase-locking dynamics.

        Parameters
        ----------
        dt:
            Discrete time step for phase evolution.

        Returns
        -------
        float:
            Global molecular coherence of the cluster.
        """
        if dt <= 0:
            raise ValueError("dt must be positive.")

        # Standard Kuramoto-style phase difference:
        # theta_j - theta_i.
        phase_difference = (
            self.molecular_phases[None, :]
            - self.molecular_phases[:, None]
        )

        # Baseline coupling represents primary molecular affinity.
        baseline_coupling = np.ones(
            (self.num_resonators, self.num_resonators),
            dtype=np.float64,
        )

        # Effective coupling combines baseline affinity with medium memory.
        total_coupling = (
            baseline_coupling + self.medium_memory_tensor
        ) / (1.0 + self.eta)

        # Remove self-coupling.
        np.fill_diagonal(total_coupling, 0.0)

        # Dynamic phase modulation of the molecular oscillator group.
        phase_acceleration = np.sum(
            total_coupling * np.sin(phase_difference),
            axis=1,
        )

        self.molecular_phases = (
            self.molecular_phases
            + (self.atomic_frequencies + phase_acceleration) * dt
        ) % (2.0 * np.pi)

        # Reconstruct the molecular phase-bonding matrix.
        updated_phase_difference = (
            self.molecular_phases[:, None]
            - self.molecular_phases[None, :]
        )

        self.binding_matrix = np.cos(updated_phase_difference)
        np.fill_diagonal(self.binding_matrix, 0.0)

        molecular_coherence = np.abs(
            np.mean(np.exp(1j * self.molecular_phases))
        )

        self._update_chemical_appearance(
            molecular_coherence=molecular_coherence,
        )

        return float(molecular_coherence)

    def _update_chemical_appearance(
        self,
        molecular_coherence: float,
    ) -> None:
        """
        Update the chemical appearance index.

        The chemical appearance index describes how strongly the molecular
        phase-bonding structure is manifested as a retained chemical regime.

        It combines:
        - global molecular phase coherence,
        - active phase-bond density,
        - accumulated memory of the liquid medium,
        - viscosity damping of the medium.
        """
        positive_bonds = self.binding_matrix > 0.85

        active_bond_density = float(
            np.sum(positive_bonds)
            / max(1, self.num_resonators * (self.num_resonators - 1))
        )

        medium_memory_strength = float(
            np.mean(np.abs(self.medium_memory_tensor))
        )

        viscosity_penalty = 1.0 / (1.0 + self.eta)

        self.chemical_appearance_index = float(
            molecular_coherence
            * (1.0 + active_bond_density)
            * (1.0 + medium_memory_strength)
            * viscosity_penalty
        )

    def calculate_chemical_appearance(self) -> dict[str, float | str]:
        """
        Calculate the current appearance state of the molecular cluster.

        Returns
        -------
        dict[str, float | str]:
            Chemical appearance index, bonding regime, active bond density,
            medium memory strength, and viscosity damping factor.
        """
        positive_bonds = self.binding_matrix > 0.85

        active_bond_density = float(
            np.sum(positive_bonds)
            / max(1, self.num_resonators * (self.num_resonators - 1))
        )

        medium_memory_strength = float(
            np.mean(np.abs(self.medium_memory_tensor))
        )

        viscosity_penalty = 1.0 / (1.0 + self.eta)

        if self.chemical_appearance_index >= 1.2:
            bonding_regime = "STABLE CHEMICAL PHASE MANIFESTATION"
        elif self.chemical_appearance_index >= 0.6:
            bonding_regime = "PARTIAL CHEMICAL PHASE MANIFESTATION"
        else:
            bonding_regime = "WEAK OR UNSTABLE CHEMICAL PHASE MANIFESTATION"

        return {
            "chemical_appearance_index": float(
                self.chemical_appearance_index
            ),
            "bonding_regime": bonding_regime,
            "active_bond_density": active_bond_density,
            "medium_memory_strength": medium_memory_strength,
            "viscosity_penalty": float(viscosity_penalty),
        }

    def demanifest_chemical_bonds(self) -> None:
        """
        Dissolve chemical phase bonds through phase unlocking.
        """
        print(
            "[MOLECULAR] Molecular coherence is being released. "
            "The cluster transitions into uncoupled phase modes."
        )

        self.binding_matrix = np.zeros(
            (self.num_resonators, self.num_resonators),
            dtype=np.float64,
        )

        self.medium_memory_tensor *= 0.0
        self.chemical_appearance_index = 0.0


if __name__ == "__main__":
    macro_continuum = ContinuumSimulation(
        num_layers=4,
        dt=0.01,
        seed=42,
    )

    dna_oscillator = WaveGeneticsDNAOscillator(
        sequence_length=32,
        base_frequency=320.0,
        seed=76,
    )

    molecular_cluster = MolecularPhaseChemistry(
        num_resonators=32,
        medium_viscosity=0.1,
        seed=144,
    )

    print("=== MOLECULAR PHASE CHEMISTRY WITH APPEARANCE LAYER ===")

    system_coherence = macro_continuum.update_state(
        coupling_strength=12.0,
        external_pressure=0.0,
    )

    j_flux = macro_continuum.M * system_coherence

    biophoton_signal, hologram_density = dna_oscillator.emit_biophotons(
        j_flux=j_flux,
        brain_modulation_frequency=7.83,
    )

    phantom_coherence = dna_oscillator.stabilize_phantom(
        modulated_signal=biophoton_signal,
        current_system_coherence=system_coherence,
    )

    molecular_cluster.apply_biophoton_forcing(
        biophoton_signal=biophoton_signal,
        phantom_coherence=phantom_coherence,
    )

    print(
        "\n[SIMULATION] Starting molecular phase alignment "
        "inside the liquid medium..."
    )

    for step in range(4):
        molecular_coherence = molecular_cluster.synchronize_molecular_bonds(
            dt=0.02,
        )

        appearance_state = molecular_cluster.calculate_chemical_appearance()

        print(
            f"Step {step} | "
            f"Molecular coherence: {molecular_coherence:.4f} | "
            f"Chemical appearance index: "
            f"{appearance_state['chemical_appearance_index']:.4f}"
        )

        print(
            f"       -> Bonding regime: "
            f"{appearance_state['bonding_regime']}"
        )

        print(
            f"       -> Active bond density: "
            f"{appearance_state['active_bond_density']:.4f} | "
            f"Medium memory strength: "
            f"{appearance_state['medium_memory_strength']:.4f}"
        )

    print(
        "\n[INFO] Molecular phase-chemistry simulation completed. "
        f"Hologram density: {hologram_density:.4f} | "
        f"Phantom coherence: {phantom_coherence:.4f}"
    )
